name: CI/CD Demo pipeline logbook1

# define when the workflow is triggered on a push to main branch, a PR to main or manually.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 # workflow_dispatch:

# simulations of jobs per environment

jobs:
  Build:                                            # whenever we push to either feature or main branch compilation is triggered
    name: Build Image
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::488646421363:role/gtactions
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecrgatest
        IMAGE_TAG: test_image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        

# deployment to development environment

  DeployDev:
    name: Deploy to development2
    if: github.event_name == 'pull_request'   #will deploy to development environment only when a pull request to main is created as specified in "on"
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Deploy
        run: echo code is being deployed to dev


  # deployment to staging environment when a push in main (a merge is a push) occurs
  DeployStaging:                                   
    name : Deploy to staging environment              
    if: github.event.ref == 'refs/heads/main' 
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Deploy
        run: echo code is being deployed to Staging

  # deploying to production if approved manually
  DeployProduction:
    name: Deploy to production
    if: github.event.ref == 'refs/heads/main'  # it will deploy only when code is pushed to main
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy
        run: echo code deployed to Production
